package com.storagehub.domain.model;

public enum ReservationStatus {
    AWAITING_EMAIL,
    AWAITING_REVIEW,
    AWAITING_PAYMENT,
    PAYMENT_GRACE,
    PAYMENT_REVIEW,
    CONFIRMED,
    UNIT_RESERVED,
    READY_FOR_CHECKIN,
    AWAITING_CUSTOMER_RECEIPT,
    COMPLETED,
    CANCELLED,
    EXPIRED,
    REJECTED
}
